### ISSUE TITLE
Doc link on README.md doesn't work

### ISSUE THREAD

**Issue by GameO7er** [nobitex/docs-api#3]
In the README.md file you wrote http://apidocs.nobitex.market that it's ok but when user click on link it will redirect to https://apidocs.nobitex.net/ link that doesn't exist and gives 404 error.
please change 
`[http://apidocs.nobitex.market](https://apidocs.nobitex.net)`
to
`[https://apidocs.nobitex.market](https://apidocs.nobitex.market)`

**Comment by MohammadHasani** [comment]
@GameO7er Thanks for your reply.
The correct address is [https://nobitex.market/api/#api](https://nobitex.market/api/) and now README.md file updated.

**Comment by amiraliakbari** [comment]
For reference, from now we have moved the API documentation to this location: [https://apidocs.nobitex.market](https://apidocs.nobitex.market).

The link in README file is also updated to point to the new location. The root cause of the problem was a configuration problem in our Travis CI that is fixed in 92031bd.
